### ISSUE TITLE
Pushing not working for MYZ commands

### ISSUE THREAD

**Issue by 9littlebees** [Stefouch/sebedius-myz-discord-bot#12]
Rolling !r or !roll doesn't bring up the push reaction.

**Comment by 9littlebees** [comment]
Never mind, the server owner didn't set the correct permissions. Fixed now.

**Comment by Stefouch** [comment]
> Never mind, the server owner didn't set the correct permissions. Fixed now.

Did the server owner disabled the permission, or was it missing from the bot's install ?

**Comment by 9littlebees** [comment]
Sorry, I missed your earlier message somehow. The permission had been disabled by the owner, nothing was wrong with the bot.
