### ISSUE TITLE
Not able to add the bot to the server due to verification/gateway problem

### ISSUE THREAD

**Issue by SenpaiDash** [Stefouch/sebedius-myz-discord-bot#215]
### Which command was used?

Adding the discord bot

### Issue Description

![VerifyProblem](https://github.com/user-attachments/assets/5da66196-eda7-468c-9305-92c4d693892a)

- Not able to add bot to my server

### Priority this issue should have?

Critical (bot crash, extremely major functional impact)

### Bot's Permissions

- [X] I confirm that I checked the bot's permissions

**Comment by Stefouch** [comment]
Hi! Thank you for your report!
It should be fixed by now.
