### ISSUE TITLE
Some used emoji are no longer valid

### ISSUE THREAD

**Issue by aramis-erak** [Stefouch/sebedius-myz-discord-bot#34]
When using the vaesen environment, a "!roll 3d6" gets error emoji placeholders for the dice faces.
This is the result:
![image](https://user-images.githubusercontent.com/43119398/91366329-512b1c80-e7b8-11ea-8619-104ac8d9005f.png)
This is after clicking the placeholder:
![image](https://user-images.githubusercontent.com/43119398/91366378-699b3700-e7b8-11ea-9d5f-f28a456ba1a3.png)

**Comment by Stefouch** [comment]
Hi @aramis-erak !

You have to type `!roll 3d` instead of `3d6`. Drop the `6` in the end.

If you only type a number + a letter, the bot recognize that as a Year Zero roll. Otherwise, it sees a generic roll to parse.

**Comment by Stefouch** [comment]
Oh! I might have misunderstood your issue.

This is not an emoji error placeholder. This is my actual emoji to represent a D6. :roll_eyes: 

The message about the privacy/unavailability of the emoji is normal. The emojis the bot uses are from another private server. Bots can use all emojis from all servers they joined. But not members. So Discord is just saying that you can see the emoji, but it's not available to you.

**Comment by aramis-erak** [comment]
I’m not seeing the emoji  in the dice details – I’m seeing just black squares.

Sent from Mail for Windows 10

**Comment by Stefouch** [comment]
The black square *is* the emoji. :sweat_smile: Sorry, it's ugly!

That black square is my representation of a Six-sided die (for now).

**Comment by Stefouch** [comment]
If you roll `!roll d12+d10+d8+d6+1` you'll see all the other icons for the dice.
